services:
  - type: web
    name: curi-engine-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn curi_engine.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: curi-engine-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
